CREATE DATABASE HOSPITAL;

CREATE TABLE DEPARTMENT(
DEPARTMENTID INT PRIMARY KEY,
DEPARTMENTNAME VARCHAR(100) NOT NULL,

);

CREATE TABLE PATIENTS (
PATIENTID INT PRIMARY KEY,
GENDER VARCHAR(10),
PATIENTNAME VARCHAR(100) NOT NULL,
BLOODGROUP VARCHAR(5),
AGE INT
);

-- Multivalued attribute for Patient Phone Numbers

CREATE TABLE PATIENT_PHONE(
PATIENTID INT,
PHONE VARCHAR(10),
PRIMARY KEY (PATIENTID,PHONE),
FOREIGN KEY (PATIENTID) REFERENCES PATIENTS(PATIENTID)
);

CREATE TABLE DOCTOR (
DOCTORID INT PRIMARY KEY,
PROFESSIONAL_DETAILS TEXT,
SPECIALIZATION VARCHAR(100),
SCHEDULES TEXT,
DEPARTMENTID INT,
MANAGERID INT,
FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID),

FOREIGN KEY (MANAGERID) REFERENCES DOCTOR(DOCTORID)

);

CREATE TABLE INSURANCE (
 INSURANCEID INT PRIMARY KEY,
 PROVIDERNAME VARCHAR(100),
 PATIENTID INT,
 FOREIGN KEY (PATIENTID) REFERENCES PATIENTS(PATIENTID)
);

CREATE TABLE APPOINTMENT (
APPOINTMENTID INT PRIMARY KEY,
TYPE VARCHAR(50),
TIME TIME,
DATE DATE,
SCHEDULED SMALLINT CHECK (SCHEDULED IN (0,1)),
COMPLETED SMALLINT CHECK (COMPLETED IN (0,1)),
CANCELLED SMALLINT CHECK (CANCELLED IN (0,1)),
NO_SHOW SMALLINT CHECK (NO_SHOW IN (0,1)),
PATIENTID INT,
DOCTORID INT,
FOREIGN KEY (PATIENTID) REFERENCES PATIENTS(PATIENTID),
FOREIGN KEY (DOCTORID) REFERENCES DOCTOR(DOCTORID)
);


CREATE TABLE BILLING (
BILLINGID INT PRIMARY KEY,
AMOUNT DECIMAL(10, 2),
VISA SMALLINT CHECK (VISA IN (0,1)),
CASH SMALLINT CHECK (CASH IN (0,1)),
APPOINTMENTID INT,
FOREIGN KEY (APPOINTMENTID) REFERENCES APPOINTMENT(APPOINTMENTID)
);

